// React/src/Home.js
import React from 'react';
import FhirClientProvider from './FhirClientProvider';
import Patient from './Patient';

/* All components wrapped inside FhirClientProvider has access
 to the fhir client through the context */
export default function Home() {
  return (
    <FhirClientProvider>
      <Patient />
    </FhirClientProvider>
  );
}

// Svelte/src/Home.svelte
<script>  
    import { context } from "./stores.js";      
    import './smart-on-fhir';
    import Patient from "./components/Patient.svelte";    

    let error = null;

    $: {
        error = $context?.error;
    }
</script>

{#if error != null}
    <p>{error}</p>    
{:else}
    <Patient/>
{/if}
